### ISSUE TITLE
Custom file or method for adding a domain

### ISSUE THREAD

**Issue by AgentCosmic** [vboctor/disposable_email_checker#15]
We should be able to maintain our own list of domains that we want to exclude without touching the data files.

Thanks.

**Comment by vboctor** [comment]
Can you provide an example of what you are trying to achieve?  I'm unclear about the scenario for the request.

**Comment by AgentCosmic** [comment]
Something like
DisposableEmailChecker::add_data_source('domains.txt');
or
DisposableEmailChecker::add_domains([...domains]);

**Comment by vboctor** [comment]
I have opted for implementing the add_domains(array) and remove_domains(array).  Thanks for the suggestion.
